services:
  - type: web
    name: online-assessment-round1
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run build
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: "postgresql://neondb_owner:npg_VqvEyua1JCz3@ep-cool-dew-b3gswcml-pooler.c-4.ap-southeast-1.aws.neon.tech/neondb?sslmode=require"
      - key: JWT_SECRET
        generateValue: true
